### ISSUE TITLE
Stuck on Setting the controller to learning mode...

### ISSUE THREAD

**Issue by BenJamesAndo** [EduardoHerreraM/SmartIR-Zigbee-Tools#2]
Hello. Thanks so much for making this!
I've got Python 3.11.7 running on Windows 11. I have all the dependencies installed.
When I run `poetry run python app/main.py` it then returns:
```Set the device to `off` mode```
```Setting the controller to learning mode...```

But nothing after that happens. My UFO-R11 doesn't go into learning mode. Am I doing something wrong? I've also tried it with Python 3.10 and Python 3.12. I'm also running Mosquitto and Zigbee2MQTT. I have `poetry 1.7.1` installed.
I do have moes_ufo_r11_controller.py in \app\src\domain\controllers and have set my env variables.

My best guess is that it's not connecting to Mosquitto at all. Nothing shows up in the logs of Zigbee2MQTT. If I run the following service in Home Assistant it does go into learning mode
```
service: mqtt.publish
data:
  topic: zigbee2mqtt/moes_ufo_r11/set
  payload: "{\"learn_ir_code\": \"ON\"}"
```
